export interface AspekLegalInterface {
  noAktaPendirian:string,
  tanggalTerbitAktaPendirian: string,
  notarisAktaPendirian: string,
  notarisPenggantiAktaPendirian: string,
  noAktaPerubahan: string,
  tanggalTerbitAktaPerubahan: string,
  notarisAktaPerubahan: string,
  notarisPenggantiAktaPerubahan:string,
  noSkPengesahanMenteri: string,
  tanggalTerbitNoSkPengesahanMenteri: string,
  npwp: string,
  tanggalTerbitNpwp: string,
  noSiup: string,
  tanggalTerbitSiup: string,
  noNibTdp: string,
  isNiBTdpSeumurHidup: boolean,
  tanggalTerbitNibTdp: string,
  tanggalExpireNibTdp: string,
  noIdpSitu: string,
  isIdpSituSeumurHidup: boolean,
  tanggalTerbitIdpSitu: string,
  tanggalExpireIdpSitu: string
}