apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-stack: eproc
    app: eproc-fe
  name: eproc-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eproc-fe
  template:
    metadata:
      labels:
        app: eproc-fe
    spec:
      containers:
      - image: 
        name: eproc-fe
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 128m
            memory: 64Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecrcred
---
apiVersion: v1
kind: Service
metadata:
  name: eproc-fe
  labels:
    app-stack: eproc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  # - port: 443
  #   protocol: TCP
  #   name: https
  selector:
    app: eproc-fe