FROM mcr.microsoft.com/playwright:focal as build-stage
LABEL stage="builder"
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:stable-alpine as build-prod
WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/dist/eproc-fe .
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]